# Generated by Django 2.1.7 on 2019-04-08 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
