# Generated by Django 2.1.7 on 2019-04-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_set',
            field=models.BooleanField(default=False),
        ),
    ]
