# Generated by Django 2.1.7 on 2019-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='slug',
            field=models.SlugField(default=None),
        ),
    ]
