# Generated by Django 2.1.7 on 2019-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_hackathon_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='slug',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
