# Generated by Django 2.1.7 on 2019-04-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_auto_20190407_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='slug',
            new_name='name_id',
        ),
    ]
