# Generated by Django 2.1.7 on 2019-04-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('name', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(default=None, max_length=200)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('desc', models.TextField(default=None, max_length=500)),
                ('poster', models.FileField(upload_to='poster/')),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisers.Organiser')),
            ],
        ),
    ]
