# Generated by Django 2.1.7 on 2019-04-07 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisers', '0002_hackathon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='organiser',
        ),
        migrations.DeleteModel(
            name='Hackathon',
        ),
    ]
