# Generated by Django 2.1.7 on 2019-03-19 17:42

from django.db import migrations, models
import participants.models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='github_username',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='participant',
            name='institution',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='participant',
            name='linkedin_url',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='participant',
            name='locality',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='participant',
            name='resume',
            field=models.FileField(default=None, upload_to=participants.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
