# Generated by Django 2.1.7 on 2019-04-07 05:37

from django.db import migrations, models
import participants.models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_auto_20190319_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='resume',
            field=models.FileField(upload_to=participants.models.user_directory_path),
        ),
    ]
